language: python

jobs:
  include:
    - if: branch = main AND env(TRAVIS_EVENT_TYPE) != cron
      python: 3.6
    - if: branch = main AND env(TRAVIS_EVENT_TYPE) != cron
      python: 3.7
    - if: branch = main AND env(TRAVIS_EVENT_TYPE) != cron
      python: 3.8
    - python: 3.9
    - if: branch = main AND env(TRAVIS_EVENT_TYPE) != cron
      python: "nightly"
    - if: branch = main AND env(TRAVIS_EVENT_TYPE) != cron
      python: "pypy3"
    - if: branch = main AND env(TRAVIS_EVENT_TYPE) != cron
      os: osx
      osx_image: xcode12.2
      language: shell
    - if: branch = main AND env(TRAVIS_EVENT_TYPE) != cron
      os: windows
      language: shell
      before_install:
        - choco install python3 --version 3.9.2
      env: PATH=/c/Python39:/c/Python39/Scripts:$PATH
  
  allow_failures:
    - python: "nightly"
  
  fast_finish: true


install:
  - pip3 install .

script:
  - export NewYorkTimesAPIKey=$NewYorkTimesAPIKey
  - python3 tests.py || python tests.py
