name: Run short tests

on: [pull_request]

jobs:
  linux-testing:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12", "pypy-3.10"]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .
      - name: Run unit tests
        env:
          NewYorkTimesAPIKey: ${{ secrets.API_KEY }}
        run: |
          python tests.py
